### ISSUE TITLE
Problems with spacing in IP Statement (PhD branch)

### ISSUE THREAD

**Issue by ksuchak1990** [stonerlab/Thesis-template#2]
I have just cloned down a copy of the PhD branch and started making modifications such as changing author name, school, etc. When compiling to PDF, I have found that there are some issues with spacing in a couple of places in the IP statement:
1. No space after author name in 3rd paragraph.
2. Problems with spacing around the copyright and year in the final line.

I have solved these issues for myself locally; 1 just requires that we call `theAuthor` as a command, i.e. `\theAuthor{}`, and 2 can be solved with a similar approach of calling `\copyright` as a command + using `\the\year{}` to get the current year.

I'm very happy to fork, commit and make a pull request for a fix if appropriate (assuming that this is reproducible for others).

**Comment by gb119** [comment]
Thanks, I've patched in some fixes:
(1) Actually I've done \theAuthor\ - the trailing \ forces LaTeX to terminate the command there and thus the space becomes a space and not the termination of the command. I think {} effectively does the same by enclosing zer content.
(2) I've done something similar around trhe copyright - I've picked up your \the\year but finish it with a trailing \, but also added a trailing slash to \copyright to force a space there - personally I don't like the year butting up on the (C) symbol.
